### ISSUE TITLE
[Bug] Mod Blocks Unsupported

### ISSUE THREAD

**Issue by ghost** [josephcsible/DegradeExplodedBlocks#2]
When putting blocks from other mods in the config, I get the following log message;

[main/WARN] [degradeexplodedblocks]: Ignoring replacement with unknown old block: quark:soul_sandstone * minecraft:soul_sand

**Comment by josephcsible** [comment]
Yeah, this was the exact same bug as josephcsible/PistonCompression#4. I should have realized it affected this mod too. Fixed in 1.0.1. (Again, if you're impatient, grab it from [the releases page](https://github.com/josephcsible/DegradeExplodedBlocks/releases)).
